# Generated by Django 2.2 on 2021-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
